apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-logging
  namespace: kube-logging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "le-issuer"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 5601
    host: kibana.k8s.mevijay.dev
  tls:
  - hosts:
    - kibana.k8s.mevijay.dev
    secretName: tls-kibana
